remote_theme: ronv/sidey
plugins:
  - jekyll-remote-theme
site: Jonathan Gheller
url: gheller.com
title: Jonathan Gheller
description: Simple and minimalistic jekyll blogging theme.
twitter:
  username: jgheller
  card: summary
  creator: jgheller
author:
  twitter: jgheller
  name: Jonathan Gheller
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  
  - jekyll-remote-theme

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"